# Generated by Django 4.1.3 on 2022-11-18 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Registration_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.marks'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_details', to='Student.marks'),
        ),
    ]
