# Generated by Django 4.1.3 on 2022-11-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_feedback_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_details',
            name='S_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='Student.student_details'),
        ),
    ]
