# Generated by Django 4.1 on 2022-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_admission_details_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='S_name',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='photo',
            field=models.ImageField(upload_to='media/img'),
        ),
    ]
