# Generated by Django 4.1 on 2022-11-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_admission_details_s_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_details',
            old_name='Reg_No',
            new_name='registration_No',
        ),
    ]
