# Generated by Django 4.1 on 2022-11-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_teacher_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_details',
            old_name='Teacher_id',
            new_name='position',
        ),
    ]
