# Generated by Django 4.1 on 2022-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_rename_teacher_id_teacher_details_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_details',
            name='department',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
