# Generated by Django 4.1 on 2022-11-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_teacher_details_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_Details',
        ),
    ]
